### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-html-terminal-and-git-_u9ftI#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-html-terminal-and-git-_u9ftI/) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

Most excited I've ever been for a class at MSU.

**Comment by stuartpearman** [comment]
Thanks Griffin! Hopefully we have some more lessons up soon, excited for the semester.

And yep, project checks out :shipit:
